### ISSUE TITLE
Missing GCC linker scripts

### ISSUE THREAD

**Issue by gparmeggiani** [STMicroelectronics/cmsis_device_f4#10]
the startup `.s` files refer to symbols defined in the linker script, but where is the linker script(s)?

**Comment by TOUNSTM** [comment]
Hello @gparmeggiani,

Thank you for your contribution. For the GCC linker scripts, you can find these within each example, or they can be generated using STM32CubeMX. I hope this answers your question. Please allow me to close this issue.

With regards,

**Comment by gparmeggiani** [comment]
Hello

Thanks for the reply. 

I'm sorry but this is not an acceptable solution to me.

Other of your repos have the linker scripts in that folder, see: 
- https://github.com/STMicroelectronics/cmsis_device_f1/tree/master/Source/Templates/gcc
- https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates/gcc

**Comment by gparmeggiani** [comment]
Please reopen

**Comment by TOUNSTM** [comment]
Hello @gparmeggiani,

At the initial stages of the Dual core development, the GCC linker files from CubeFW were used. However, they were quickly replaced by an independent process that generates them via the CubeIDE project generator. Consequently, our technical team does not intend to add GCC linker files for legacy products such as the STM32F4 series. Therefore, I will maintain the status of this thread as closed.

Thank you for your comprehension and thank you again for having reported.

With Regards,

**Comment by TOUNSTM** [comment]
See Also [STM32CubeG0#43](https://github.com/STMicroelectronics/STM32CubeG0/issues/43)

**Comment by gparmeggiani** [comment]
Not everybody wants to use the CubeIDE workflow.

Anyways I have to accept your answer and figure out how to move forwards in my project.

As a final note, please consider 
1) aligning this to all your `cmsis_device_*` projects: either all of them have the linker scripts or none of them.
2) removing the linker script from other compiler folders, e.g. https://github.com/STMicroelectronics/cmsis_device_f4/tree/master/Source/Templates/iar/linker
3) Documenting this decision somewhere

Thanks for your time and prompt responses.
