### ISSUE TITLE
Wrong value for FLASH_ACR_LATENCY_Msk in stm32f407xx.h

### ISSUE THREAD

**Issue by GodFacker** [STMicroelectronics/cmsis_device_f4#2]
**Describe the bug**

`#define FLASH_ACR_LATENCY_Msk          (0xFUL << FLASH_ACR_LATENCY_Pos)         /*!< 0x0000000F */`

there are only 3 bits

`#define FLASH_ACR_LATENCY_Msk          (0x7UL << FLASH_ACR_LATENCY_Pos)         /*!< 0x00000007 */`

maybe it's not critical but misleading

**Comment by RKOUSTM** [comment]
Hi @GodFacker,

The issue you pointed out has been confirmed, a fix will be implemented and made available in future release. Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 101040

**Comment by RKOUSTM** [comment]
Hi @GodFacker,

I hope you are fine. The issue you reported has been fixed in the frame of version v2.6.6 of the cmsis_device_f4  published recently on GitHub.

Thank you again for having reported.

With regards,
