### ISSUE TITLE
Typo in definition of __STM32F4xx_CMSIS_VERSION

### ISSUE THREAD

**Issue by svijsv** [STMicroelectronics/cmsis_device_f4#6]
The definition of __STM32F4xx_CMSIS_VERSION in stm32f4xx.h reads
`#define __STM32F4xx_CMSIS_VERSION        ((__STM32F4xx_CMSIS_VERSION_MAIN << 24)\
                                         |(__STM32F4xx_CMSIS_VERSION_SUB1 << 16)\
                                         |(__STM32F4xx_CMSIS_VERSION_SUB2 << 8 )\
                                         |(__STM32F4xx_CMSIS_VERSION))`
resulting in a compilation error when used. It should instead read
`#define __STM32F4xx_CMSIS_VERSION        ((__STM32F4xx_CMSIS_VERSION_MAIN << 24)\
                                         |(__STM32F4xx_CMSIS_VERSION_SUB1 << 16)\
                                         |(__STM32F4xx_CMSIS_VERSION_SUB2 << 8 )\
                                         |(__STM32F4xx_CMSIS_VERSION_RC))`

**Comment by ASELSTM** [comment]
Hi @svijsv,

The issue you pointed out has been confirmed, a fix will be implemented and made available in future release. Thank you once again for your contribution.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 110625

**Comment by carlo-dev-git** [comment]
I suggest to close this issue because it was fixed months ago.
https://github.com/STMicroelectronics/cmsis_device_f4/blob/7ac69098b3e5f9b2d929acd4f087e92a7e59e0e9/Include/stm32f4xx.h#L110-L117

**Comment by ASELSTM** [comment]
Hi @svijsv,

As this issue has been fixed please allow me then to close this thread.

Thank you again for your contribution.

With regards,
