### ISSUE TITLE
stm32f412cx: lack of MCO2 bits definition

### ISSUE THREAD

**Issue by niedzwiecki-dawid** [STMicroelectronics/cmsis_device_f4#9]
According to RM0402, all STM32F412 chips can configure MCO2 in RCC_CFGR register. 

The [stm32f412cx.h](https://github.com/STMicroelectronics/cmsis_device_f4/blob/master/Include/stm32f412cx.h#L8485) header doesn't have the definition of MCO2 bits. I guess it is done this way because all stm32f412cx chips are in UFQFPN48 package, which doesn't have PC9 pin (MCO2 pin). 

The problem is that changing the MCO2 source clock(to a clock that is disabled) [reduces](https://community.st.com/t5/stm32-mcus-products/stm32412cg-ufqfpn48-mco2-unexpected-power-consumption/m-p/622027) power consumption. 

Wouldn't it make sense to define the MCO2 bits for all STM32F412 bit despite the fact the PC9 pin is not present?

**Comment by niedzwiecki-dawid** [comment]
Is there any plan to take care of this issue?

**Comment by TOUNSTM** [comment]
ST Internal Reference: 170618

**Comment by TOUNSTM** [comment]
Fixed in commit 2e1724e592931693ce4dfc43e2fd6b3bc375d6a0

**Comment by niedzwiecki-dawid** [comment]
Thanks.
